#!/usr/bin/env python

"""
Use "Reservoir Sampling" to return `k` random lines from the input files (or
stdin if no input files are passed on the command line).
See: https://en.wikipedia.org/wiki/Reservoir_sampling

Run `subset --help` for info.
"""

import argparse
import fileinput
import sys


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Subset file(s) using Reservoir Sampling")
    parser.add_argument('-k', '--num_lines', required=True,
                        help='number of samples (lines) to keep from the input file(s)')
    parser.add_argument('files', metavar='FILE', nargs='*',
                        help='files to read; if empty, uses stdin')
    args = parser.parse_args()

    k = args.num_lines
    samples = []

    for line in fileinput.input(files=args.files):
        if i < k:
            samples.append(line.rstrip('\n'))
        else:
            r = random.randint(0, i)
            if r < k:
                samples[r] = line.rstrip('\n')

    sys.stdout.write('\n'.join(samples))

